name: "Publish package"

on:
  release:
    types:
      - created
    tags:
      - "v[0-9]+"
      - "v[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14.16.0'
          registry-url: "https://npm.pkg.github.com"
          # Defaults to the user or organization that owns the workflow file
          scope: "@zondax"
      - name: Install yarn
        run: npm install -g yarn
      - name: Install modules
        run: yarn install
      - name: Build package
        run: yarn build
      - name: Get latest release version number
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Update tag
        run: npm --no-git-tag-version version ${{ steps.get_version.outputs.version }}
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
